import {NgModule}      from '@angular/core'
import {BrowserModule} from '@angular/platform-browser';
import {FormsModule}   from '@angular/forms';
import {ProjectComponent} from './project.component';
import {RouterModule} from "@angular/router";

import {
  SharedModule,
  AccordionModule,
  AutoCompleteModule,
  BlockUIModule,
  BreadcrumbModule,
  ButtonModule,
  CalendarModule,
  CarouselModule,
  ChartModule,
  CheckboxModule,
  ChipsModule,
  CodeHighlighterModule,
  ContextMenuModule,
  DataGridModule,
  DataListModule,
  DataScrollerModule,
  DataTableModule,
  ConfirmDialogModule,
  DialogModule,
  DragDropModule,
  DropdownModule,
  EditorModule,
  FieldsetModule,
  FileUploadModule,
  GalleriaModule,
  GMapModule,
  GrowlModule,
  InplaceModule,
  InputMaskModule,
  InputSwitchModule,
  InputTextModule,
  InputTextareaModule,
  LightboxModule,
  ListboxModule,
  MegaMenuModule,
  MenuModule,
  MenubarModule,
  MessagesModule,
  MultiSelectModule,
  OrderListModule,
  OverlayPanelModule,
  PaginatorModule,
  PanelModule,
  PanelMenuModule,
  PasswordModule,
  PickListModule,
  ProgressBarModule,
  RadioButtonModule,
  RatingModule,
  ScheduleModule,
  SelectButtonModule,
  SlideMenuModule,
  SliderModule,
  SpinnerModule,
  SplitButtonModule,
  StepsModule,
  TabViewModule,
  TabMenuModule,
  TerminalModule,
  TieredMenuModule,
  ToggleButtonModule,
  ToolbarModule,
  TooltipModule,
  TreeModule,
  TreeTableModule,
  TriStateCheckboxModule
} from 'primeng/primeng';
import {ProjectComponentService} from "./project.component.service";

@NgModule({
  declarations: [
    ProjectComponent
  ],
  imports: [
    RouterModule,
    BrowserModule,
    FormsModule,
    SharedModule,
    // AccordionModule,
    // AutoCompleteModule,
    // BlockUIModule,
    // BreadcrumbModule,
    ButtonModule,
    CalendarModule,
    // CarouselModule,
    // ChartModule,
    // CheckboxModule,
    // ChipsModule,
    // CodeHighlighterModule,
    // ContextMenuModule,
    // DataGridModule,
    // DataListModule,
    // DataScrollerModule,
    DataTableModule,
    ConfirmDialogModule,
    DialogModule,
    // DragDropModule,
    DropdownModule,
    // EditorModule,
    // FieldsetModule,
    // FileUploadModule,
    // GalleriaModule,
    // GMapModule,
    // GrowlModule,
    // InplaceModule,
    // InputMaskModule,
    // InputSwitchModule,
    InputTextModule,
    InputTextareaModule,
    // LightboxModule,
    ListboxModule,
    // MegaMenuModule,
    // MenuModule,
    // MenubarModule,
    // MessagesModule,
    // MultiSelectModule,
    // OrderListModule,
    // OverlayPanelModule,
    PaginatorModule,
    // PanelModule,
    // PanelMenuModule,
    PasswordModule,
    // PickListModule,
    // ProgressBarModule,
    RadioButtonModule,
    // RatingModule,
    // ScheduleModule,
    // SelectButtonModule,
    // SlideMenuModule,
    // SliderModule,
    // SpinnerModule,
    // SplitButtonModule,
    // StepsModule,
    // TabViewModule,
    // TabMenuModule,
    // TerminalModule,
    // TieredMenuModule,
    // ToggleButtonModule,
    // ToolbarModule,
    // TooltipModule,
    // TreeModule,
    // TreeTableModule,
    TriStateCheckboxModule
  ],
  exports: [
    ProjectComponent
  ],
  bootstrap: [ProjectComponent],
  providers: [ProjectComponentService]
})
export class ProjectModule {
}
